# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac6746fe4f1bfb0a0457e17ecf2374e68537b6fa70a51a14feb4c495ca8000daeab1c30d32264a5ae7d5ea5adfc9568d66b95efd1e11707c51b48dc58db8f283

test:
  secret_key_base: 2b03aafe6fcf9f0232ef5b2103690d56ff5aee423a5cad33c9f7ab7f4eb780da838d861a47998861441bc978c788311be8c5d657ce68317de152c3888bb891c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
